spring.application.name=springPracticalDemo

spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=mysqlpassword

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true

jwt.secret=XN3qY/mLtQ6WhHoPeA+6IY7szRI9iI4HFdCP/lO+B0U=
jwt.issuer=secret-api
jwt.expiry=900